-- Tienda: productos, pedidos y sus líneas, con el catálogo inicial.
-- Los pedidos guardan el nombre y el precio de cada producto tal como se compró.
-- Idempotente: se puede aplicar sobre una base existente tantas veces como haga falta.
--   mariadb reserva_eventos_bbdd < reto-eventos-backend/migraciones/2026-10-09-tienda.sql

CREATE TABLE IF NOT EXISTS productos (
	id_producto INT AUTO_INCREMENT PRIMARY KEY,
	slug VARCHAR(60) NOT NULL UNIQUE,
	nombre VARCHAR(80) NOT NULL,
	categoria VARCHAR(12) NOT NULL,
	resumen VARCHAR(160) NOT NULL,
	descripcion TEXT NOT NULL,
	procedencia VARCHAR(120) NOT NULL,
	formato VARCHAR(40) NOT NULL,
	lote VARCHAR(20) NOT NULL,
	conservacion VARCHAR(200) NOT NULL,
	distribucion VARCHAR(160) NOT NULL,
	advertencia VARCHAR(200),
	precio DECIMAL(9,2) NOT NULL,
	existencias INT NOT NULL DEFAULT 0,
	tono VARCHAR(12) NOT NULL,
	orden INT NOT NULL DEFAULT 0,
	activo BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT ck_producto_categoria CHECK (categoria IN ('LECHE', 'DERIVADO', 'MESA')),
	CONSTRAINT ck_producto_precio CHECK (precio >= 0),
	CONSTRAINT ck_producto_existencias CHECK (existencias >= 0)
);

CREATE TABLE IF NOT EXISTS pedidos (
	id_pedido INT AUTO_INCREMENT PRIMARY KEY,
	referencia VARCHAR(20) UNIQUE,
	username VARCHAR(45) NOT NULL,
	estado VARCHAR(12) NOT NULL,
	entrega VARCHAR(12) NOT NULL,
	direccion VARCHAR(200),
	subtotal DECIMAL(9,2) NOT NULL,
	gastos_envio DECIMAL(9,2) NOT NULL,
	total DECIMAL(9,2) NOT NULL,
	creado_en DATETIME NOT NULL,
	anulado_en DATETIME,
	CONSTRAINT fk_pedidos_usuarios FOREIGN KEY (username) REFERENCES usuarios(username),
	CONSTRAINT ck_pedido_estado CHECK (estado IN ('CONFIRMADO', 'ENVIADO', 'ENTREGADO', 'ANULADO')),
	CONSTRAINT ck_pedido_entrega CHECK (entrega IN ('ENVIO', 'RECOGIDA')),
	INDEX idx_pedidos_usuario (username, creado_en)
);

CREATE TABLE IF NOT EXISTS lineas_pedido (
	id_linea INT AUTO_INCREMENT PRIMARY KEY,
	id_pedido INT NOT NULL,
	id_producto INT NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	precio_unitario DECIMAL(9,2) NOT NULL,
	cantidad INT NOT NULL,
	importe DECIMAL(9,2) NOT NULL,
	CONSTRAINT fk_lineas_pedidos FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido) ON DELETE CASCADE,
	CONSTRAINT fk_lineas_productos FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
	CONSTRAINT ck_linea_cantidad CHECK (cantidad > 0)
);

-- tono: color de la muestra en el frontend (features/shop/shop-shared.css).
INSERT IGNORE INTO productos
	(slug, nombre, categoria, resumen, descripcion, procedencia, formato, lote, conservacion, distribucion, advertencia, precio, existencias, tono, orden)
VALUES
('leche-entera-ceto-iv', 'Leche entera de Ceto IV', 'LECHE',
	'La leche de referencia de la casa, ordeñada a mano y sin homogeneizar.',
	'Procede de la granja asociada de Ceto IV, donde el ordeño sigue haciéndose a mano y de madrugada. No se homogeneiza: la nata sube a la superficie en unas horas y conviene agitar la botella con suavidad antes de servir. Es ligeramente salina, con un final de almendra tostada, y es la que se sirve al principio de cada sesión para que el paladar tenga un punto de partida.',
	'Ceto IV · Granja asociada', '750 ml', 'AM-L-0427',
	'Entre 2 y 5 °C. Una vez abierta, consumir en un plazo de tres días.',
	'Todos los territorios con cadena de frío garantizada.',
	'Contiene lactosa. Puede contener trazas de plancton.',
	6.40, 148, 'nacar', 1),
('leche-de-pelagia', 'Leche de Pelagia', 'LECHE',
	'Densa, muy fría al paladar y de un azul pálido que se aclara con el aire.',
	'Se obtiene en la Estación Pelagia de organismos de aguas profundas que la producen para alimentar a sus crías durante la travesía. Es densa y fría al paladar, de un azul muy pálido que se aclara al contacto con el aire. Se sirve sin hielo y en copa estrecha, que conserva mejor el frío.',
	'Estación Pelagia · AE03, Lagos', '500 ml', 'AM-L-0512',
	'Entre 2 y 5 °C, en posición vertical. No congelar.',
	'Limitada a territorios con puerto refrigerado.',
	'Agitar con suavidad. Si se agita con energía emite un zumbido breve; es normal.',
	9.80, 37, 'glaciar', 2),
('leche-simbiotica-de-liquen', 'Leche simbiótica de liquen', 'LECHE',
	'La producen dos organismos a la vez. Ninguno de los dos acepta la autoría.',
	'Este liquen de los valles de TRAPPIST-1e es, en realidad, dos organismos que viven juntos desde hace cuatro mil años. La leche la producen entre los dos, y cada cosecha sabe distinta según cuál haya llevado la iniciativa: unas veces herbácea, otras casi dulce. Se recomienda probarla sola, a temperatura de bodega.',
	'TRAPPIST-1e · Valle de Hesse', '330 ml', 'AM-L-0388',
	'Entre 8 y 12 °C, lejos de la luz directa.',
	'Todos los territorios.',
	'Producto vivo. La botella puede cambiar ligeramente de color durante el transporte.',
	7.20, 8, 'liquen', 3),
('mantequilla-cultivada', 'Mantequilla cultivada', 'DERIVADO',
	'Batida con la nata de la leche de la casa y madurada durante dos días.',
	'Se bate a partir de la nata de la leche de Ceto IV, la misma que se sirve en las sesiones, y se madura durante dos días con cultivos de la propia granja. El resultado es una mantequilla de color pálido, con una acidez suave y un fondo salino que recuerda a su procedencia.',
	'Ceto IV · Granja asociada', '250 g', 'AM-D-0119',
	'Entre 2 y 5 °C. Sacar del frío diez minutos antes de servir.',
	'Todos los territorios con cadena de frío garantizada.',
	'Contiene lactosa y sal marina de origen.',
	8.50, 64, 'mantequilla', 4),
('queso-de-cueva-de-gliese', 'Queso de cueva de Gliese', 'DERIVADO',
	'Catorce meses en unas cuevas donde la temperatura no ha cambiado en tres siglos.',
	'Se madura durante catorce meses en las cuevas de la meseta de Ossar, en Gliese 667 Cc, a pocos kilómetros de la sede central. La temperatura de las cuevas no ha cambiado en tres siglos, y se nota en la corteza: fina, seca y de un gris casi azul. La pasta es firme, con notas de nuez y de piedra húmeda.',
	'Gliese 667 Cc · Meseta de Ossar', 'Pieza de 200 g', 'AM-D-0074',
	'Entre 4 y 8 °C, envuelto en papel. Nunca en plástico.',
	'Transporte refrigerado a cargo de Frío Gliese.',
	'Contiene leche cruda.',
	14.90, 0, 'piedra', 5),
('kefir-de-tau-ceti', 'Kéfir de Tau Ceti', 'DERIVADO',
	'Fermentado con granos cedidos por la Federación de Catadores de Tau Ceti.',
	'Los granos con los que se fermenta proceden de la Federación de Catadores de Tau Ceti, que los cede a AlienMilk desde hace once ciclos. Es ligero, de burbuja fina y final ácido. Su sabor cambia ligeramente según quién lo pruebe; la Federación lo considera una virtud.',
	'Tau Ceti · Federación de Catadores', '500 ml', 'AM-D-0131',
	'Entre 2 y 5 °C. Abrir despacio: el fermento sigue activo.',
	'Todos los territorios con cadena de frío garantizada.',
	'No apto para organismos que compartan el sentido del gusto.',
	6.90, 52, 'lila', 6),
('copa-de-degustacion', 'Copa de degustación', 'MESA',
	'La copa de las sesiones: boca estrecha para el aroma, base ancha para las leches densas.',
	'Es la copa que se usa en todas las sesiones de AlienMilk. La boca estrecha concentra el aroma y la base ancha deja que las leches más densas se asienten sin formar capas. Se sopla a mano en un taller de A Coruña, así que no hay dos exactamente iguales.',
	'Tierra · Taller de vidrio de A Coruña', '180 ml', 'AM-M-0023',
	'Apta para lavavajillas. Secar boca abajo.',
	'Todos los territorios.',
	'Vidrio soplado: las pequeñas burbujas del cristal son propias del proceso.',
	18.00, 90, 'cristal', 7),
('estuche-isotermico', 'Estuche isotérmico', 'MESA',
	'Mantiene dos botellas entre 2 y 5 °C durante 48 horas, en cualquier gravedad.',
	'Diseñado junto a Frío Gliese, el operador que transporta las leches de AlienMilk entre sistemas. Mantiene dos botellas de hasta 750 ml entre 2 y 5 °C durante 48 horas, sin hielo ni corriente. El cierre está pensado para manos de cualquier forma.',
	'Gliese 667 Cc · Frío Gliese', 'Dos botellas', 'AM-M-0007',
	'Limpiar con un paño húmedo. No sumergir.',
	'Todos los territorios.',
	'Conserva el frío, no lo genera: introduzca las botellas ya refrigeradas.',
	32.00, 25, 'grafito', 8),
('catalogo-de-procedencias', 'Catálogo de procedencias 2026', 'MESA',
	'Las procedencias del archivo, con su organismo de origen y sus notas de cata.',
	'Reúne las procedencias del archivo de AlienMilk tal como se catalogan en la sede central: organismo de origen, método de extracción, notas de cata y ficha de conservación de cada muestra. Edición en tapa dura, revisada para el ciclo 2026, con un índice por sistemas.',
	'Archivo AlienMilk · Estación Meridiana', '312 páginas', 'AM-M-0031',
	'Lejos de la humedad y de las leches abiertas.',
	'Todos los territorios.',
	'Algunas fichas incluyen ilustraciones a tamaño real.',
	24.00, 120, 'papel', 9);
